name: Instagram Reels Bot

on:
  schedule:
    # Run at 9:00 AM and 3:00 PM UTC (adjust for your timezone)
    - cron: '0 9 * * *'
    - cron: '0 15 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests schedule yt-dlp pathlib
        # Install any additional dependencies your bot needs
    
    - name: Create necessary directories
      run: |
        mkdir -p downloads
        mkdir -p backups
    
    - name: Run Instagram Bot
      env:
        INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        INSTAGRAM_PAGE_ID: ${{ secrets.INSTAGRAM_PAGE_ID }}
        INSTAGRAM_APP_ID: ${{ secrets.INSTAGRAM_APP_ID }}
        INSTAGRAM_APP_SECRET: ${{ secrets.INSTAGRAM_APP_SECRET }}
        GITHUB_ACTIONS: true
      run: python bot.py
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs
        path: |
          instagram_bot.log
          processed_posts.json
        retention-days: 30
